name: Prowler AWS Scan
on:
  workflow_dispatch:
   ## schedule:
   ## - cron: '30 18 * * *' # Runs Daily at 12:00 AM IST 

permissions:
  id-token: write
  contents: read

jobs:
  prowler-scan:
    runs-on: ubuntu-latest
    steps:

    # 1. Checkout repo
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Set up AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  

    # Verify Access
    - name: Verify AWS Access
      run: aws sts get-caller-identity

    # 4. Install Prowler
    - name: Install Prowler
      run: pip install -r prowler-scan/requirements.txt

    - name: Verify Installation
      run: prowler --version  

    # 5. Run Prowler
    - name: Run Prowler Scan
      run: |
        mkdir -p output         
        prowler aws \
          --config-file ./prowler-scan/config/config.yaml \
          --checks-file ./prowler-scan/config/checklist.yaml \
          --output-directory output \
          --output-modes html json-ocsf \
          --output-filename prowler-report \
          --ignore-exit-code-3 \
          --region ap-south-1  

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: prowler-report
        path: output/       

    # Send Report
    - name: Send Prowler Report Email
      env:
        AWS_REGION: ap-south-1
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ vars.EMAIL_TO }}
        S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
        REPORT_DIR: output
      run: python prowler-scan/scripts/send_report.py
